include(
    ":voyager-core",
    ":voyager-screenmodel",
    ":voyager-navigator",
    ":voyager-lifecycle-kmp",
    ":voyager-tab-navigator",
    ":voyager-bottom-sheet-navigator",
    ":voyager-transitions",
    ":voyager-hilt",
    ":voyager-kodein",
    ":voyager-koin",
    ":voyager-rxjava",
    ":voyager-livedata"
)
